language: swift

osx_image: xcode10.0
env:
  matrix:
    - TEST_SDK=iphonesimulator12.0 OS=12.0 NAME='iPhone XR'
    - TEST_SDK=iphonesimulator12.0 OS=12.0 NAME='iPhone 7'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project Booster.xcodeproj -scheme Booster -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES